### ISSUE TITLE
Light 2 doesn't cast own light field.

### ISSUE THREAD

**Issue by KieranER** [KieranER/Cits3003Project#3]
As far as I can tell, light 2 slightly varies what's going on in light ones influence, however it doesn't actually cast any light of it's own. Separate lights to test, or dim light 1.

Also as a result, I'm not as sure about tweaking the attenuation.

**Comment by Jye-Dewar** [comment]
Are you sure, I thought that light 2 was definitely doing something from what we saw? The attenuation was set when we were last testing it, have you changed that? That does seem quite odd. Let me know how it goes and I will try fix it in the morning

**Comment by KieranER** [comment]
Ok, so first reset attenuation to a fixed 0.5, which was significantly brighter. when adjusting the brightness of light one, there's no visible light remaining the same brightness for light two. Also, moving light two around, I see a moving specular element, but no diffuse or ambient. I'll do some more tests, and see if i can get a better idea.

**Comment by KieranER** [comment]
ok, so a couple of things. A: when I removed the light 1 element from the colour completely, it appeared like light 1 was still there. If I moved light 1, everything moved, If I moved light 2, the specular for light 2 moved. I'm going to take a look at the C++ code, and see if that's where the problem is, because after looking through the shaders, my current thought is the light 1 data is being passed as light 2.

**Comment by KieranER** [comment]
pressed the wrong button there.

**Comment by KieranER** [comment]
ok, the position data itself for light 1 and 2 is fine.

**Comment by KieranER** [comment]
Ok, found what I think is the problem. Or problems, as it actually was.
Problem A, is you used the same attenuation value from light one, and that is calculated based on the distance from the object to light 1 (i.e. L1). another atten had to be made. This is why light 2 appeared to only be visible where light 1 was. Because it was being told that's where it's allowed to be bright.

Problem 2 which I haven't yet fixed: when using move light 1, and button 3 dragging left to right, it also changes the brightness of light 2, which is why originally my testing with atten set to 0.5 didn't work, as I tried dimming light 1 to see if light 2 was visible.

**Comment by KieranER** [comment]
Finally, with the attenuation function itself, It's working fine as-is, though the light 2 spotlight is very bright on it's own, and tends to bleach anything it lights up once remotely close. In any case, as ambient is coming from both lights, I'll half it's calculated value (even though it'll be diminished when only one light is near). This reduces the whiteout a little while still looking fairly good.

**Comment by Jye-Dewar** [comment]
Hmm alright then, how is part 2 going? Did you end up finding a tutorial for inserting bones in the animation

**Comment by Jye-Dewar** [comment]
Yeah no worries, hmmm it does seem like a bit of an odd problem, I can’t check now because it just won’t compile on my computer but I will definitely check it out first thing tomorrow
